<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_American Express Concierge_form-control_1</name>
   <tag></tag>
   <elementGuidId>d3db5409-5bc1-42e7-a90c-4552b13e53e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46e557ca-4193-4811-894a-d4a7b3851ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>91d2b18e-d9d0-4fa6-8a00-0aef307d3ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0d2c1a40-ad1c-4e19-8a8e-766715affef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>810291fc-8b58-48e9-b5c6-116305fa6498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;theme-hero-area&quot;]/div[@class=&quot;theme-hero-area-body&quot;]/div[@class=&quot;theme-page-section _pt-100 theme-page-section-xl&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12&quot;]/div[@class=&quot;theme-login&quot;]/div[@class=&quot;theme-login-box&quot;]/div[@class=&quot;theme-login-box-inner&quot;]/form[@class=&quot;theme-login-form&quot;]/div[@class=&quot;form-group theme-login-form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>9f787acb-3cd8-4e6b-a778-859fe43f3f2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>4ed7601b-547c-48c1-ae54-9ad19e2df1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div/div/div[2]/div/form/div[2]/input</value>
      <webElementGuid>b220b728-4f1c-4456-b026-4afcd789d256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>127af1c7-95a9-405a-aae2-70b6c96b27d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>e6d1a25a-04e2-465a-9cd9-60763a6506f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
