<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PNR_form-control</name>
   <tag></tag>
   <elementGuidId>35ce988f-4e4d-4b8f-9939-1ea75f25271e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @placeholder = 'Client ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58fb3610-f56d-45aa-82b3-26743dfbc032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9924e35d-7b1d-41dc-882b-a6e84b3275b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0945ef55-8674-4188-bae4-9b5c3be12a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Client ID</value>
      <webElementGuid>755b4218-c1e8-487e-a24b-8ac98bee05a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;theme-hero-area&quot;]/div[@class=&quot;theme-hero-area-body&quot;]/div[@class=&quot;theme-page-section _pt-100 theme-page-section-xl&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 col-md-offset-4 col-sm-7 col-sm-offset-3 col-xs-12&quot;]/div[@class=&quot;theme-login&quot;]/div[@class=&quot;theme-login-box&quot;]/div[@class=&quot;theme-login-box-inner&quot;]/form[@class=&quot;theme-login-form&quot;]/div[@class=&quot;form-group theme-login-form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>fa0f255f-6f55-4b6a-8ee4-a9993ebf491f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>d7b2958c-5abc-4c09-9122-0e9892748bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div/div/div/div[2]/div/form/div[2]/input</value>
      <webElementGuid>2f195452-19be-467e-8eba-fd19cc86d00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>79c08d93-2522-46c8-9eb7-2fa778b807f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Client ID']</value>
      <webElementGuid>775397f2-7e62-4b1e-8363-a4989c51a725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
